### ISSUE TITLE
Consider simplifying API

### ISSUE THREAD

**Issue by lpil** [dropwhile/gbase32_clockwork#1]
Hello!

This is a very simple bit of functionality from the users' point of view, but to use this library they have to import many modules. This is verbose and confusing, and the users can't read all the documentation in one place. There also seems to be some implementation detail typesthat are exposed in the package public API.

It would be great to have all the modules merged into one to make a better user experience!

Thanks,
Louis

**Comment by dropwhile** [comment]
@lpil Thanks for the comment Louis! Big fan of gleam, and I am still early in my gleam journey.

Are there any guides for best practices for things like this? Or do you have any more specific recommendations?
If not (I'm sure you are quite busy), then I'll try a round of cleanups and flatten out the hierarchy and see how it goes.

Thanks.

**Comment by lpil** [comment]
No specific guides at the moment I'm afraid. Generally I think it's good to make it as straightforward as possible from the user's point of view. I think this would often mean one module, and a handful of clearly defined functions that hide all the internals as much as possible.

**Comment by dropwhile** [comment]
@lpil I took a stab at reducing the interface complexity, and now return function partials instead of a record container for function partials.

https://hexdocs.pm/gbase32_clockwork/2.0.3/

Hopefully this improves the usability!

**Comment by lpil** [comment]
Looks good!
